name: Build and Deploy Jekyll site

on:
  push:
    branches:
      - main  # 또는 사용 중인 브랜치 이름으로 변경
  pull_request:
    branches:
      - main  # 또는 사용 중인 브랜치 이름으로 변경

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.3'  # 필요한 Ruby 버전으로 변경
    - run: gem install bundler
    - run: bundle install
    - run: bundle exec jekyll build
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
